CREATE TABLE "ad_campaigns" (
	"id" serial PRIMARY KEY NOT NULL,
	"campaign" text,
	"ad_group" text,
	"ad" text,
	"product_name" text,
	"product_url" text,
	"sku_suffix" text,
	"skus" text,
	"discount_code" text,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"utm_term" text,
	"product_template" text,
	"status" text DEFAULT 'active',
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"shopify_id" text NOT NULL,
	"order_number" text,
	"email" text,
	"customer_name" text,
	"phone" text,
	"created_at" timestamp with time zone,
	"fulfillment_status" text,
	"fulfilled_at" timestamp with time zone,
	"subtotal" numeric(10, 2),
	"shipping" numeric(10, 2),
	"tax" numeric(10, 2),
	"total" numeric(10, 2),
	"discount_codes" text,
	"skus" text,
	"quantity" integer,
	"utm_source" text,
	"utm_campaign" text,
	"utm_medium" text,
	"utm_content" text,
	"utm_term" text,
	"tracking_number" text,
	"tags" text,
	"has_conversion_data" boolean DEFAULT false,
	"received_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "orders_shopify_id_unique" UNIQUE("shopify_id")
);
