CREATE TABLE "products" (
	"id" serial PRIMARY KEY NOT NULL,
	"sku" text NOT NULL,
	"product_name" text,
	"brand" text,
	"unit_barcode" text,
	"asin" text,
	"parent_asin" text,
	"shippo_sku" text,
	"pieces_per_pack" integer,
	"pack_weight_kg" numeric(10, 3),
	"pack_length_cm" numeric(10, 2),
	"pack_width_cm" numeric(10, 2),
	"pack_height_cm" numeric(10, 2),
	"unit_cbm" numeric(10, 6),
	"dimensional_weight" numeric(10, 3),
	"unit_price_usd" numeric(10, 4),
	"unit_price_gbp" numeric(10, 4),
	"pack_cost_gbp" numeric(10, 4),
	"landed_cost" numeric(10, 4),
	"unit_lcogs" numeric(10, 4),
	"rrp" numeric(10, 2),
	"pp_unit" numeric(10, 4),
	"rrp_ex_vat" numeric(10, 2),
	"carton_barcode" text,
	"units_per_master_carton" integer,
	"pieces_per_master_carton" integer,
	"gross_weight_kg" numeric(10, 3),
	"carton_width_cm" numeric(10, 2),
	"carton_length_cm" numeric(10, 2),
	"carton_height_cm" numeric(10, 2),
	"carton_cbm" numeric(10, 6),
	"active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "products_sku_unique" UNIQUE("sku")
);
