CREATE TABLE "amazon_ads_pending_reports" (
	"id" serial PRIMARY KEY NOT NULL,
	"org_id" integer NOT NULL,
	"report_id" text NOT NULL,
	"report_date" date NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "amazon_sp_ads" (
	"id" serial PRIMARY KEY NOT NULL,
	"org_id" integer NOT NULL,
	"date" date NOT NULL,
	"campaign_id" text NOT NULL,
	"campaign_name" text,
	"campaign_status" text,
	"campaign_budget_amount" real,
	"campaign_budget_type" text,
	"campaign_budget_currency_code" text,
	"campaign_rule_based_budget_amount" real,
	"portfolio_id" text,
	"start_date" text,
	"end_date" text,
	"impressions" integer DEFAULT 0,
	"clicks" integer DEFAULT 0,
	"cost" real DEFAULT 0,
	"cost_per_click" real,
	"click_through_rate" real,
	"sales_1d" real,
	"sales_7d" real,
	"sales_14d" real,
	"sales_30d" real,
	"purchases_1d" integer,
	"purchases_7d" integer,
	"purchases_14d" integer,
	"purchases_30d" integer,
	"units_sold_clicks_1d" integer,
	"units_sold_clicks_7d" integer,
	"units_sold_clicks_14d" integer,
	"units_sold_clicks_30d" integer,
	"purchase_click_rate_1d" real,
	"purchase_click_rate_7d" real,
	"purchase_click_rate_14d" real,
	"purchase_click_rate_30d" real,
	"acos_clicks_7d" real,
	"acos_clicks_14d" real,
	"roas_clicks_7d" real,
	"roas_clicks_14d" real,
	"new_to_brand_purchases_14d" integer,
	"new_to_brand_sales_14d" real,
	"new_to_brand_units_sold_14d" integer,
	"new_to_brand_purchases_percentage_14d" real,
	"new_to_brand_sales_percentage_14d" real,
	"new_to_brand_units_sold_percentage_14d" real,
	"add_to_cart" integer,
	"add_to_cart_rate" real,
	"ecp_add_to_cart" real,
	"impressions_1y" integer,
	"clicks_1y" integer,
	"spend_1y" real,
	"cost_per_click_1y" real,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "amazon_ads_pending_reports" ADD CONSTRAINT "amazon_ads_pending_reports_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "amazon_sp_ads" ADD CONSTRAINT "amazon_sp_ads_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "amazon_sp_ads_org_date_campaign_idx" ON "amazon_sp_ads" USING btree ("org_id","date","campaign_id");